### ISSUE TITLE
roadmapping

### ISSUE THREAD

**Issue by serapath** [playproject-io/play-workshop#1]
## `@todo`
* [ ] overhaul design
* [ ] refactor code base
* [ ] update demo workshop
* [ ] upgrade dependent workshops with pull requests and update skilltree

---
